version: '3'
services:
  sveltekit:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh -c "yarn install && yarn dev --host"
    ports:
      - '5173:5173'
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    env_file:
      - .env.local

volumes:
  node_modules:
